# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ubx8MIyfD6RERTeYwCeIdmtlrdweQlsN
"""

import gradio as gr
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import random

"""DATA PREPROCESSING

"""

movies=pd.read_csv('/content/movie.csv')
movies.head(5)

movies.info()
movies.shape

movies.isnull().sum()

unique_genres = set("|".join(movies["genres"]).split("|"))
print("Unique Genres:", unique_genres)

all_genres = "|".join(movies["genres"]).split("|")
genre_counts = Counter(all_genres)

genre_df = pd.DataFrame(genre_counts.items(), columns=["Genre", "Count"]).sort_values(by="Count", ascending=False)


plt.figure(figsize=(12,6))
sns.barplot(x=genre_df["Count"], y=genre_df["Genre"], palette="viridis")
plt.xlabel("Number of Movies")
plt.ylabel("Genre")
plt.title("Distribution of Movie Genres")
plt.show()

no_genre_count = (movies["genres"] == "(no genres listed)").sum()
print(f"Movies without a genre: {no_genre_count}")

no_genre_movies = movies[movies["genres"] == "(no genres listed)"]
print(no_genre_movies[["movieId", "title"]])

movies.loc[movies["genres"] == "(no genres listed)", "genres"] = "Miscellaneous"

"""**CONTENT** **BASED** **FILTERING** - TF-IDF and Cosine Similarity"""

tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
tfidf_matrix = tfidf.fit_transform(movies["genres"])

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

def recommend_by_genre(genre, top_n=5):
    # Filter movies that contain the genre
    genre_movies = movies[movies["genres"].str.contains(genre, case=False, na=False)]

    # If no movies are found, return an error message
    if genre_movies.empty:
        return "Genre not found. Please enter a valid genre."

    # Randomly sample movies from the genre (up to top_n)
    return genre_movies.sample(n=min(top_n, len(genre_movies)))[["title", "genres"]]

# Example search
print(recommend_by_genre("Sci-Fi", 5))
print(recommend_by_genre("Comedy", 5))

# Gradio Interface

def genre_recommender(selected_genre):
    recommendations = recommend_by_genre(selected_genre)
    return "\n".join(recommendations["title"].tolist())

# Get unique genres from the dataset
unique_genres = set("|".join(movies["genres"]).split("|"))

# Create Gradio UI
interface = gr.Interface(
    fn=genre_recommender,
    inputs=gr.Dropdown(choices=list(unique_genres), label="Select a Genre"),
    outputs="text",
    title="🎬 Genre-Based Movie Recommendation System",
    description="Select a genre to get movie recommendations!"
)

# Launch the app
interface.launch(share=True)